### ISSUE TITLE
Appointments Reported by Script Don't Exist in Scheduler UI

### ISSUE THREAD

**Issue by seffyroff** [everettsouthwick/trusted-traveler-scheduler#18]
I'm getting Notified of appointments by the script.  When I login to book them, they don't exist, and the script continues to report their existence.

**To Reproduce**
1: Add a config for location 13321 and date 7th June 2023 (for example)
2: You will receive notification of available appointments from the script
3: Login to https://ttp.cbp.dhs.gov/ and go to reschedule interview
4: for the location configured, note that no appointments are available

**Expected behavior**
Appointments reported by script should exist in scheduler UI

**Screenshots**
![image](https://github.com/everettsouthwick/trusted-traveler-scheduler/assets/8338529/c8e477b9-4f97-4a92-afd3-771ec20481aa)
![image](https://github.com/everettsouthwick/trusted-traveler-scheduler/assets/8338529/5b1c0f81-5296-49a0-b28c-f7b60dc1997a)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Tested with Edge, Firefox, Chrome
 - Version Latest versions

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 16.5
 - Browser Safari, Firefox, Edge
 - Version Latest versions

**Additional context**
Could be location specific - I tested this with another location and the reported appointment did exist in the UI.

My config looks like this:

```json
{
  "current_appointment_date": "June 7, 2023",
  "location_ids": [ 13321 ],
  "notification_level": 1,
  "notification_urls": [ "discord://webhookurl" ],
  "retrieval_interval": "5m",
  "start_appointment_time": "00:00",
  "end_appointment_time": "23:59"
}
```
I am running the script via Docker.  Container image ecsouthwick/trusted-traveler-scheduler:latest retrieved 2023-05-24.  I have also run the script locally cloned from this repo with the same results.

**Comment by everettsouthwick** [comment]
Thank you for your detailed report! 

It looks like on the TTP website you're looking at the Blaine NEXUS and FAST Enrollment Center (ID: 5020), while the Blaine Global Entry Enrollment Center (ID: 13321) is what your script is configured to look at. That's pretty confusing, but that's the way the TTP differentiates between the two locations. I'm seeing the June 4th date available when I'm looking at the Global Entry location:

![image](https://github.com/everettsouthwick/trusted-traveler-scheduler/assets/8216991/acdfaaa8-c963-443e-a598-636cc26a0c93)

This is the URL I was using to access the Global Entry location: https://ttp.cbp.dhs.gov/schedulerui/schedule-interview/location?lang=en&vo=true&returnUrl=ttp-external&service=UP

Hope this helps! Let me know if you are still seeing this issue and I'll take another look.

**Comment by seffyroff** [comment]
Thanks! That is weird but ok. I'll update my location to the NEXUS one!

**Comment by seffyroff** [comment]
Actually, that doesn't seem to fix it - when I set my location to 5020, I'm still getting appointment notifications for Global Entry.

![image](https://github.com/everettsouthwick/trusted-traveler-scheduler/assets/8338529/c586dbe3-9806-4ecb-940f-8110b4c418cd)

**Comment by everettsouthwick** [comment]
> Actually, that doesn't seem to fix it - when I set my location to 5020, I'm still getting appointment notifications for Global Entry.
> 
> ![image](https://user-images.githubusercontent.com/8338529/242971884-c586dbe3-9806-4ecb-940f-8110b4c418cd.png)

The `-l 5020` will append 5020 to the list of locations already specified in your `config.json`, so it will include both 5020 and 13321 if your `config.json` still has 13321 in it.

**Comment by seffyroff** [comment]
Gotcha, thanks again!
