### ISSUE TITLE
sql database does not track removed availability

### ISSUE THREAD

**Issue by shuffle2** [everettsouthwick/trusted-traveler-scheduler#24]
Currently the code only ever adds (location_id, start_time) pairs to the sql database, and uses this to determine if an available appointment is newly-seen or not. This results in missing the time slot if the appointment goes through a process like:
1) appointment is newly seen and reported
2) user is beaten to the appointment by someone else / appointment is unavailable for some reason
3) appointment slot becomes available again
At 3) above, the appointment, which should be treated as new availability, is not reported to user again.

It's probably impossible to foolproof this (unless the dhs.gov API exposes some more functionality), but it would at least be nice to clear out db entries if they are missing from a newly returned API request in _get_schedule.

**Comment by everettsouthwick** [comment]
Implemented into the develop branch in #27. Will continue testing and merge into main when confident it works as intended.
